config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html  
  
  resources :products
  
  resources :films
  
  resources :galleries
  
  resources :beekeepers
  
  resources :specifications
  
  resources :articles do
     resources :comments
  end
  
  root to: "welcome#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
   
   has_many :comments, dependent: :destroy 
   
   validates :author, presence: true, length: {minimum: 3}
   validates :text, presence: true, length: {minimum: 3}   
  
end

app/models/beekeeper.rb
class Beekeeper < ApplicationRecord
   mount_uploader :image, ImageUploader    	
   mount_uploader :image1, ImageUploader	
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/film.rb
class Film < ApplicationRecord
    
	mount_uploader :video, VideoUploader
	
	validates :title, presence: true,
                     length: {minimum: 3}
	
	
    			 
				 
end

app/models/gallery.rb
class Gallery < ApplicationRecord
   mount_uploader :image, ImageUploader
   
   validates :title, presence: true, length: {minimum: 3}
   validates :image, presence: true
   
end

app/models/product.rb
class Product < ApplicationRecord
    validates :title, presence: true,
                     length: {minimum: 3}
	validates :text, presence: true,
                     length: {minimum: 3}
    
	mount_uploader :image, ImageUploader
    	
	mount_uploader :image1, ImageUploader				 
end

app/models/specification.rb
class Specification < ApplicationRecord
   mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
	before_action :authenticate_user!, except: [:index, :show]
   
   def index
     @articles = Article.all
   end
   
   def show
      @article = Article.find(params[:id])   
   end
   
   def new
     @article = Article.new
   end
   
   def create
     @article = Article.new(article_params)
		
		if (@article.save)
		    @article.update(email: current_user.email)
			redirect_to @article
        else
            render 'new'
        end	   
   end
   
   def edit
      @article = Article.find(params[:id])
   end 
   
   def update     
	 @article = Article.find(params[:id])
	 
	 if @article.update(article_params)
	    redirect_to @article
	 else
        render 'edit'
     end  
   end
   
    def destroy
	    @article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path	 
	 end
   
    private
	 
	 def article_params
	     params.require(:article).permit(:text, :email, :author)
	 
	 end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   
    before_action :authenticate_user!, except: [:index,:show]
	
   def create
     @article = Article.find(params[:article_id])
	 @comment = @article.comments.create(comment_params)
	 @comment.update(email: current_user.email)
	 redirect_to article_path(@article)
   end
   
   def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
   
   private
   
   def comment_params
    
	params.require(:comment).permit(:commenter, :body)
     
   end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
     def index
	   @films = Film.all
	 end
	 
	 def show
	   @film = Film.find(params[:id])
	 end
	 
	 def new
	   @film = Film.new
	 end
	 
	 def edit
	   @film = Film.find(params[:id])
	 end
	 
	  def update
	   @film = Film.find(params[:id])
	   
	   if @film.update(film_params) 
	      redirect_to @film
		else
           render 'edit'   
	   end
	 end
	 
	 
	 def create
	    @film = Film.new(film_params)
		
		if (@film.save)
   		  redirect_to @film
        else
            render 'new'
        end			
	 end
   
   def destroy
     @film = Film.find(params[:id])
	 @film.destroy
	 redirect_to films_path
   end
   
	
    private	
	
	 def film_params
	    params.require(:film).permit(:title,:text,:video)
	 end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
     
	 def index
	   @products = Product.all
     end
	 
	 def show
	   @product = Product.find(params[:id])
	 end
	 
	 def new
	   @product = Product.new
	 end
	 
	 def edit
	   @product = Product.find(params[:id])
	 end
	 
	 def update
	   @product = Product.find(params[:id])
	   
	   if @product.update(product_params) 
	      redirect_to @product
		else
           render 'edit'   
	   end
	 end
	 
	 def create
	    @product = Product.new(product_params)
		
		if (@product.save)
			redirect_to @product
        else
            render 'new'
        end			
	 
	 end
	 
  def destroy
     @product = Product.find(params[:id])
	 @product.destroy
	 redirect_to products_path
   end
   
	 
	 private
	 
	 def product_params
	     params.require(:product).permit(:title,:text,:image, :image1)
	 
	 end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/beekeepers_helper.rb
module BeekeepersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/specifications_helper.rb
module SpecificationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

    <% if @article.errors.any? %>
    <div class = "alert alert-danger">
      <h2>
        <%=t('common.errors')%>
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>	
 		
	<div class="form-group">
	    <%=f.label :add_text %>
		<%=f.text_area  :text, class:"form-control" %>
	</div>
	
	<div class="form-group, text-align: right">
	   <%=f.label :author %>
	   <%=f.text_field  :author, class: "form-control"%><br>
	</div>
	
	
	   
	<div class="actions">
	  <%=f.submit :'save', class:"btn btn-primary"%>
	  <%=link_to  'back', :back, class: "btn btn-secondary"%>
	</div>
	
<% end %>

app/views/articles/edit.html.erb
<h5>Editing post</h5>
<%= render 'form' %>

app/views/articles/index.html.erb
 <%@val = 'Blog' %>
	   <% @articles.each do |article| %>
		 <article class="post">
	         <section class="post-additional col-lg-12">
	            <%=article.text%><br>
				<%=link_to 'Discusion...', article_path(article) %>
			      <section class="home"> 
				   <small>
					author:
					<i><%=article.author %></i>
					|
					<time><%= article.updated_at.to_date %></time>
					
			       </small>
                  </section> 
              </section>     
	       </article><br>  				   
		<%end%>	
	<nav class="navbar main">
	  
	  
	  
		 <div class="actions">
			<%= link_to 'Add post', new_article_path, class: "btn btn-primary"%>
		 </div>
	  
	     
	  </section>
    </nav>		

    
		

	

app/views/articles/new.html.erb
<h5>New post</h5>
<%= render 'form' %>

app/views/articles/show.html.erb
<%@val = 'Blog' %>
<article class="post">
  <section class="post-body">	
	
	<section class="post-text clearfix">  
		 <div class="col-lg-12">
		   <%=@article.text %><br>
		   		 
        </div>    
         			
    </section>
  	
    <section class="post-head">	
		<small>
		     author:
			<i><%=@article.author %></i>
			|	
		    <time><%= @article.updated_at.to_date.to_date.strftime("%d, %B, %Y") %></time>
		<% if  user_signed_in? %>
           <% if  current_user.admin? %>
		    |
            <%=@article.email %>		   
			|
			<%=link_to 'Edit', edit_article_path(@article)%>
			|
			<%=link_to 'Delete', article_path(@article), method: :delete, data:{confirm: 'A You sure?'} %>
		   <% end %>
        <% end %>		   
			|
		     <%=link_to  'Back', :back, class: "btn btn-secondary"%>
		</small>
	</section>
 </article>  	

		
	
    
        <%= render @article.comments %><br>
    
	
    
		<strong><i>Add a comment:</i></strong>
		<%= render 'comments/form' %>
	 
	
 	
 

app/views/comments/_comment.html.erb
 <section class="post-additional">	
	  <i><strong> Commenter: </strong></i>
	  <%= comment.commenter %><br>
	  
	  <%= comment.body %><br>
	  
    <% if  user_signed_in? %>
     <% if  current_user.admin? %>
	 <%= comment.email %><br>
	  <%= link_to 'Delete comment', [comment.article, comment],
				   method: :delete,
				   data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
	  <%end%>
    <%end%>	  
  </section>				   
  
   				   

app/views/comments/_form.html.erb
<section class="form-group, text-align: right">	
	<%= form_for([@article, @article.comments.build]) do |f| %> 
	  <div class="form-group">
		<%= f.label :commenter %>
		<%= f.text_field :commenter, class: "form-control" %>
		<%= f.label :text %>
		<%= f.text_area :body, class: "form-control" %>
	  </div>	
		<div class="actions">
			<%= f.submit 'Create comment', class: "btn btn-primary"%>
		</div>
	       	
	<% end %>
</section> 	

app/views/comments/show.html.erb
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 
<h2>Comments</h2>
<%= render @article.comments %>
 
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
 
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/films/_form.html.erb
<%= form_for @film do |f| %>

    <% if @film.errors.any? %>
    <div class = "alert alert-danger">
      <h2>
        <%=t('common.errors')%>
      </h2>
      <ul>
        <% @film.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>	

    <div class="form-group">
	   <strong><%= f.label :'title:' %></strong><br>
	   <%= f.text_field :title, class:"form-control", size: 35 %>	   
	</div>	
	
	<div class="form-group">
	   <%=f.file_field :video %>
	   <%=f.text_area  :text, class:"form-control", cols: 35, rows: 5 %>
	</div>
	
	
	<div class="form-group">
	  <%=f.submit :'save', class:"btn btn-primary"%>
	  <%=link_to  'back', :back, class: "btn btn-secondary"%>
	</div>
	
<%end%>	

app/views/films/edit.html.erb
<strong>Editing video</strong>

<%= render 'form'%>

app/views/films/index.html.erb
<%@val = 'Video' %>
<% @films.each do |film|%>
 <article class="post">
		<section class="post-head">	  
				<strong><%= film.title %></strong><br>			
				<%= film.text %><br>
                <%=link_to 'Click for show', film_path(film)%>				
				 
		</section>
	
 </article>		
 <%end%><br>


<% if  user_signed_in? %>
 <% if  current_user.admin? %>
   <div class="actions">  
	<%=link_to 'Add video', new_film_path, class:"btn btn-primary"%>
   </div>	
 <%end%>
<%end%>	


	
	

app/views/films/new.html.erb
<strong>New video</strong>

<%= render 'form' %>

app/views/films/show.html.erb
<%@val = 'Video' %>
<article class="post">
	<section class="post-head">	
			<br>
			<strong><%= @film.title %></strong><br>
		
	</section><br>	
	<section class="post-text clearfix">
      <div class="col-lg-12 ">		   
			   <%= video_tag @film.video_url.to_s, :controls =>true, style:"max-width: 100%; max-hight: 100%" if @film.video? %>
			   <%= @film.text %>
	  </div>		  
    </section">    			
   <section class="post-head">	
	<small>	
        <% if  user_signed_in? %>
          <% if  current_user.admin? %>	
			<%=link_to 'Edit', edit_film_path(@film)%>
			|
			<%=link_to 'Delete', film_path(@film), method: :delete, data:{confirm: 'A You sure?'} %>
			|
		  <%end%>
        <%end%>		  
			<%=link_to  'back', :back, class: "btn btn-secondary"%>
		</small>
  </section> 
		
</article>					 

app/views/products/_form.html.erb
<%= form_for @product, html: {multipart: true} do |f| %>

<% if @product.errors.any? %>
    <div class = "alert alert-danger">
      <h2>
        <%=t('common.errors')%>
      </h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>	

 
	<div class="form-group">
	   <strong><%= f.label :'title:' %></strong><br>
	   <%= f.text_field :title, class:"form-control", size: 70 %>	   
	</div>	
			
	<div class="form-group">
	   <strong><%= f.label :'first image:' %></strong><br>
	   <%=f.file_field :image %>
	 </div>
	
	<div class="form-group">
	    <strong><%= f.label :'second image:' %></strong><br>
	    <%=f.file_field :image1 %>	
	</div>
	
	<div class="form-group">
	   <strong><%= f.label :'text:' %></strong><br>
	   <%=f.text_area  :text, class:"form-control", cols: 75, rows: 5 %>
	</div>
	
	<div class="form-group">
	  <%=f.submit :'save', class:"btn btn-primary"%>
	  <%=link_to  'back', :back, class: "btn btn-secondary"%>
	  
	</div>
	
<% end %>

app/views/products/edit.html.erb
<strong>Editing product</strong>

<%= render 'form' %>


app/views/products/index.html.erb
<%@val = 'About UBB'%>
<article class="post">
 <% @products.each do |product| %>	
   	<section class="post-head">	
             <br>
			 
			 <% if  user_signed_in? %>
                <% if  current_user.admin? %>
                   <h5><%= link_to product.title, product_path(product) %></h5>
				<% else %>
                   	<h5><%= product.title %></h5>			
                <% end %>
					
			  <% else %>
				     <h5><%= product.title %></h5>
			 <% end %>		 
		
	</section>
	
	<section class="post-text justify">  
		 
		<div class="row">  
		  
		   <%=image_tag product.image.url(:thumb), class: "img-thumbnail thumb", style:"max-width: 100%; max-hight: 100%; padding-left: 6em; padding-right:6em" if product.image?%>
		   <%=image_tag product.image1.url(:thumb), class: "img-thumbnail thumb", style:"max-width: 100%; max-hight: 100%; padding-left: 6em; padding-right:6em" if product.image1?%>
		  
		</end>
        
            <%= product.text %>         			
    </section> 	
  <%end%>
</article><br>

<% if  user_signed_in? %>
 <% if  current_user.admin? %>
   <div class="actions">  
	<%=link_to 'Add product', new_product_path, class:"btn btn-primary"%>
	</div>
 <%end%>
<%end%>	

	
	



app/views/products/index_.html.erb

<% @products.each do |product| %>	
 <article class="post">
   	<section class="post-head">	
             <br>	
	         <h3><%= link_to product.title, product_path(product) %></h3>
		
	</section>
	
	<section class="post-text clearfix">  
		 <div class="row">
		  <div class="col-lg-6">
		   <%=image_tag product.image.url(:thumb), class: "img-thumbnail thumb" if product.image?%>
		  </div>
		 <div class="col-lg-6">
		   <%=image_tag product.image1.url(:thumb), class: "img-thumbnail thumb" if product.image1?%>
		 </div> 
        </div>
            <%= product.text %>         			
    </section> 
	
 </article>		
 <%end%>
<%=link_to 'Add product', new_product_path%>

	
	



app/views/products/new.html.erb
<h3>New product</h3>

<%= render 'form'%>


	

app/views/products/show.html.erb
<%@val = 'Main features'%>
<article class="post">	
 <section class="post-body">
          <section class="post-head ">
		      <%= @product.title %><br> 
		  </section>
	
	<section class="post-text clearfix">  
		 <div class="row">
		  
		   <%=image_tag @product.image.url(:thumb), class: "img-thumbnail thumb", style: "height: 30em; width: 30em" if @product.image?%>
		  
		
		   <%=image_tag @product.image1.url(:thumb), class: "img-thumbnail thumb" , style: "height: 30em; width: 30em" if @product.image1?%>
		 
        </div>
            <%= @product.text %>
         			
    </section>	
	
	
	
   

<section class="post-head ">	
			
		<small>
		    <%=link_to 'Edit', edit_product_path(@product)%>
			|
		    <%=link_to 'Delete', product_path(@product), method: :delete, data:{confirm: 'A You sure?'} %>
			|
		    <%=link_to  'Back', :back, class: "btn btn-secondary"%></strong>
		</small>
	</section>   
</article>		
				 