config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html  
  
  resources :products
  
  resources :films
  
  resources :galleries
  
  resources :beekeepers
  
  resources :specifications
  
  resources :articles do
     resources :comments
  end
  
  root to: "welcome#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
   
   has_many :comments, dependent: :destroy 
   
   validates :author, presence: true, length: {minimum: 3}
   validates :text, presence: true, length: {minimum: 3}   
  
end

app/models/beekeeper.rb
class Beekeeper < ApplicationRecord
   mount_uploader :image, ImageUploader    	
   mount_uploader :image1, ImageUploader	
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/film.rb
class Film < ApplicationRecord
    
	mount_uploader :video, VideoUploader
	
	validates :title, presence: true,
                     length: {minimum: 3}
	
	
    			 
				 
end

app/models/gallery.rb
class Gallery < ApplicationRecord
   mount_uploader :image, ImageUploader
   
   validates :title, presence: true, length: {minimum: 3}
   validates :image, presence: true
   
end

app/models/product.rb
class Product < ApplicationRecord
    validates :title, presence: true,
                     length: {minimum: 3}
	validates :text, presence: true,
                     length: {minimum: 3}
    
	mount_uploader :image, ImageUploader
    	
	mount_uploader :image1, ImageUploader				 
end

app/models/specification.rb
class Specification < ApplicationRecord
   mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
	before_action :authenticate_user!, except: [:index, :show]
   
   def index
     @articles = Article.all
   end
   
   def show
      @article = Article.find(params[:id])   
   end
   
   def new
     @article = Article.new
   end
   
   def create
     @article = Article.new(article_params)
		
		if (@article.save)
		    @article.update(email: current_user.email)
			redirect_to @article
        else
            render 'new'
        end	   
   end
   
   def edit
      @article = Article.find(params[:id])
   end 
   
   def update     
	 @article = Article.find(params[:id])
	 
	 if @article.update(article_params)
	    redirect_to @article
	 else
        render 'edit'
     end  
   end
   
    def destroy
	    @article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path	 
	 end
   
    private
	 
	 def article_params
	     params.require(:article).permit(:text, :email, :author)
	 
	 end
end

app/controllers/beekeepers_controller.rb
class BeekeepersController < ApplicationController
   
   def index 
      @beekeepers = Beekeeper.all
   end
   
   def show
     @beekeeper = Beekeeper.find(params[:id])
   end
   
   def new
     @beekeeper = Beekeeper.new
   end
   
   def create
   
     @beekeeper = Beekeeper.new(beekeeper_params)
		
		if (@beekeeper.save)
		    redirect_to @beekeeper
        else
            render 'new'
        end	   
   end
   
   def edit
      @beekeeper = Beekeeper.find(params[:id])
   end
   
   def update 
     @beekeeper = Beekeeper.find(params[:id])
	 
	 if  @beekeeper.update(beekeeper_params)
	     redirect_to @beekeeper	 
	 else
	     render 'edit'
	 end
   
   end
   
   def destroy
      @beekeeper = Beekeeper.find(params[:id])
	  
	  @beekeeper.destroy
	  redirect_to @beekeepers_path

   end
   
   private
   
   def beekeeper_params
     params.require(:beekeeper).permit(:title,:text,:url1,:url2,:url3,:image, :image1)
      
   end

 end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   
    before_action :authenticate_user!, except: [:index,:show]
	
   def create
     @article = Article.find(params[:article_id])
	 @comment = @article.comments.create(comment_params)
	 @comment.update(email: current_user.email)
	 redirect_to article_path(@article)
   end
   
   def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
   
   private
   
   def comment_params
    
	params.require(:comment).permit(:commenter, :body)
     
   end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
     def index
	   @films = Film.all
	 end
	 
	 def show
	   @film = Film.find(params[:id])
	 end
	 
	 def new
	   @film = Film.new
	 end
	 
	 def edit
	   @film = Film.find(params[:id])
	 end
	 
	  def update
	   @film = Film.find(params[:id])
	   
	   if @film.update(film_params) 
	      redirect_to @film
		else
           render 'edit'   
	   end
	 end
	 
	 
	 def create
	    @film = Film.new(film_params)
		
		if (@film.save)
   		  redirect_to @film
        else
            render 'new'
        end			
	 end
   
   def destroy
     @film = Film.find(params[:id])
	 @film.destroy
	 redirect_to films_path
   end
   
	
    private	
	
	 def film_params
	    params.require(:film).permit(:title,:text,:video)
	 end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/beekeepers_helper.rb
module BeekeepersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/specifications_helper.rb
module SpecificationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/beekeepers/_form.html.erb
<%= form_for @beekeeper, html: {multipart: true} do |f| %>

  <div class="form-group">
	   <strong><%= f.label :'title:' %></strong><br>
	   <%= f.text_field :title, class:"form-control" %>	   
	</div>	
			
	<div class="form-group">
	   <strong><%= f.label :'first image:' %></strong><br>
	   <%=f.file_field :image %>
	 </div>
	
	<div class="form-group">
	    <strong><%= f.label :'second image:' %></strong><br>
	    <%=f.file_field :image1 %>	
	</div>
	
	<div class="form-group">
	   <strong><%= f.label :'text:' %></strong><br>
	   <%=f.text_area  :text, class:"form-control" %>
	</div>
	
	<div class="form-group">
	   <strong><%= f.label :'first label:' %></strong><br>
	   <%=f.url_field  :url1, class:"form-control" %>
	</div>
	
	<div class="form-group">
	   <strong><%= f.label :'second label' %></strong><br>
	   <%=f.url_field  :url2, class:"form-control" %>
	</div>
	<div class="form-group">
	   <strong><%= f.label :'third label:' %></strong><br>
	   <%=f.url_field  :url3, class:"form-control" %>
	</div>
	
	<div class="form-group">
	  <%=f.submit :'save', class:"btn btn-primary"%>
	  <%=link_to  'back', :back, class: "btn btn-secondary"%>
	  
	</div>
<%end%>

app/views/beekeepers/edit.html.erb
<h5>Editing beekeeper</h5>

<%= render 'form' %>

app/views/beekeepers/edit_.html.erb
<h5>Editing beekeepers</h5>

<%= form_for :beekeeper, url: beekeeper_path(@beekeeper), method: :patch, html: {multipart: true} do |f| %>

  <div class="form-group">
	   <strong><%= f.label :'title:' %></strong><br>
	   <%= f.text_field :title, class:"form-control" %>	   
	</div>	
			
	<div class="form-group">
	   <strong><%= f.label :'first image:' %></strong><br>
	   <%=f.file_field :image %>
	 </div>
	
	<div class="form-group">
	    <strong><%= f.label :'second image:' %></strong><br>
	    <%=f.file_field :image1 %>	
	</div>
	
	<div class="form-group">
	   <strong><%= f.label :'text:' %></strong><br>
	   <%=f.text_area  :text, class:"form-control" %>
	</div>
	
	<div class="form-group">
	   <strong><%= f.label :'first label:' %></strong><br>
	   <%=f.url_field  :url1, class:"form-control" %>
	</div>
	
	<div class="form-group">
	   <strong><%= f.label :'second label' %></strong><br>
	   <%=f.url_field  :url2, class:"form-control" %>
	</div>
	<div class="form-group">
	   <strong><%= f.label :'third label:' %></strong><br>
	   <%=f.url_field  :url3, class:"form-control" %>
	</div>
	
	<div class="form-group">
	  <%=f.submit :'save', class:"btn btn-primary"%>
	  <%=link_to  'back', :back, class: "btn btn-secondary"%>
	  
	</div>
<%end%>

app/views/beekeepers/index.html.erb
<%@val = 'About US'%>

 <% @beekeepers.each do |beekeeper| %>
  <article class="post"> 
   	<section class="post-head">	
             <br>
			 
			 <% if  user_signed_in? %>
                <% if  current_user.admin? %>
                   <h5><%= link_to beekeeper.title, beekeeper_path(beekeeper) %></h5>
				<% else %>
                   	<h5><%= beekeeper.title %></h5>			
                <% end %>
					
			  <% else %>
				     <h5><%= beekeeper.title %></h5>
			 <% end %>		 
		
	</section>
	
	<section class="post-text justify">  
		 
		<div class="row">  
		  <div class="col-lg-6"> 
		   <%=image_tag beekeeper.image.url(:thumb), class: "img-thumbnail thumb", style: "height: 100%; width: 100%"  if beekeeper.image?%>
		  </div>
		  <div class="col-lg-6"> 
		   <%=image_tag beekeeper.image1.url(:thumb), class: "img-thumbnail thumb", style: "height: 100%; width: 100%" if beekeeper.image1?%>
		  </div>
		</end>    
                     			
    </section>
    <%= beekeeper.text %> 
   
   <div class="row">
	  <div class="col-lg-4">
           <%str1 = "facebook" if beekeeper.url1.include?("facebook")%>
		   <%str1 = "linkedin" if beekeeper.url1.include?("linkedin")%>
		   <%str1 = "instagram" if beekeeper.url1.include?("instagram")%>
		   <%str1 = "twitter" if beekeeper.url1.include?("twitter")%>
		   
		  <%=link_to str1, beekeeper.url1, data: { confirm: "Are you sure?" } if beekeeper.url1? %>
	   </div>
		<div class="col-lg-4">
		
		   <%str2 = "facebook" if beekeeper.url2.include?("facebook")%>
		   <%str2 = "linkedin" if beekeeper.url2.include?("linkedin")%>
		   <%str2 = "instagram" if beekeeper.url2.include?("instagram")%>
		   <%str2 = "twitter" if beekeeper.url2.include?("twitter")%>
		   
		  <%=link_to str2, beekeeper.url2, data: { confirm: "Are you sure?" } if beekeeper.url2? %>
		</div> 
		<div class="col-lg-4">
		  
		   <%str3 = "facebook" if beekeeper.url3.include?("facebook")%>
		   <%str3 = "linkedin" if beekeeper.url3.include?("linkedin")%>
		   <%str3 = "instagram" if beekeeper.url3.include?("instagram")%>
		   <%str3 = "twitter" if beekeeper.url3.include?("twitter")%>
		
		  <%=link_to str3, beekeeper.url3, data: { confirm: "Are you sure?" } if beekeeper.url3? %>
		</div>
   </div>

 </article><br>	
  <%end%>


 

<% if  user_signed_in? %>
 <% if  current_user.admin? %>
    <div class="actions"> 
	   <%=link_to 'Add beekeeper', new_beekeeper_path, class:"btn btn-primary"%>
	</div>
 <%end%>
<%end%>	

	
	



app/views/beekeepers/new.html.erb
<h5>New beekeeper</h5>

<%= render 'form' %>


app/views/beekeepers/new_.html.erb
<h5>New beekeeper</h5>

<%= form_for :beekeeper, url: beekeepers_path, html: {multipart: true} do |f| %>

  <div class="form-group">
	   <strong><%= f.label :'title:' %></strong><br>
	   <%= f.text_field :title, class:"form-control" %>	   
	</div>	
			
	<div class="form-group">
	   <strong><%= f.label :'first image:' %></strong><br>
	   <%=f.file_field :image %>
	 </div>
	
	<div class="form-group">
	    <strong><%= f.label :'second image:' %></strong><br>
	    <%=f.file_field :image1 %>	
	</div>
	
	<div class="form-group">
	   <strong><%= f.label :'text:' %></strong><br>
	   <%=f.text_area  :text, class:"form-control" %>
	</div>
	
	<div class="form-group">
	   <strong><%= f.label :'first label:' %></strong><br>
	   <%=f.url_field  :url1, class:"form-control" %>
	</div>
	
	<div class="form-group">
	   <strong><%= f.label :'second label' %></strong><br>
	   <%=f.url_field  :url2, class:"form-control" %>
	</div>
	<div class="form-group">
	   <strong><%= f.label :'third label:' %></strong><br>
	   <%=f.url_field  :url3, class:"form-control" %>
	</div>
	
	<div class="form-group">
	  <%=f.submit :'save', class:"btn btn-primary"%>
	  <%=link_to  'back', :back, class: "btn btn-secondary"%>
	  
	</div>
<%end%>

app/views/beekeepers/show.html.erb
<%@val = 'About us'%>

  <article class="post">
  
		 <section class="post-head "> 
			<%= @beekeeper.title %>
		 </section>	
				 
			 
		<section class="post-text clearfix"> 	 
			 <div class="row ">		  
		       <div class="col-lg-6">
				   <%=image_tag @beekeeper.image.url(:thumb), class: "img-thumbnail thumb ", style: "height: 100%; width: 100%" if @beekeeper.image?%>
			   </div>
			   <div class="col-lg-6">
				   <%=image_tag @beekeeper.image1.url(:thumb), class: "img-thumbnail thumb ",  style: "height: 100%; width: 100%"  if @beekeeper.image1?%>
		       </div> 
		      </div> 	 
	     
		      <%= @beekeeper.text %>
		</section>	  
		 
         			
    
		 
		 <div class="row">
		  <div class="col-lg-4">
		   <%str1 = "facebook" if @beekeeper.url1.include?("facebook")%>
		   <%str1 = "linkedin" if @beekeeper.url1.include?("linkedin")%>
		   <%str1 = "instagram" if @beekeeper.url1.include?("instagram")%>
		   <%str1 = "twitter" if @beekeeper.url1.include?("twitter")%>
		   <%=link_to str1, @beekeeper.url1, data: { confirm: "Are you sure?" } if @beekeeper.url1? %>
		  </div>
		 <div class="col-lg-4">
		    
		   <%str2 = "facebook" if @beekeeper.url2.include?("facebook")%>
		   <%str2 = "linkedin" if @beekeeper.url2.include?("linkedin")%>
		   <%str2 = "instagram" if @beekeeper.url2.include?("instagram")%>
		   <%str2 = "twitter" if @beekeeper.url2.include?("twitter")%>
		    
		    <%=link_to str2, @beekeeper.url2, data: { confirm: "Are you sure?" } if @beekeeper.url2? %>
		 </div> 
		 <div class="col-lg-4">
		 
		   <%str3 = "facebook" if @beekeeper.url3.include?("facebook")%>
		   <%str3 = "linkedin" if @beekeeper.url3.include?("linkedin")%>
		   <%str3 = "instagram" if @beekeeper.url3.include?("instagram")%>
		   <%str3 = "twitter" if @beekeeper.url3.include?("twitter")%>		   
		  
		  <%=link_to str3, @beekeeper.url3, data: { confirm: "Are you sure?" } if @beekeeper.url3? %>
		 </div>
        </div>
     
  

		<section class="post-head ">				
			<small>
				<%=link_to 'Edit', edit_beekeeper_path(@beekeeper)%>
				|
				<%=link_to 'Delete', beekeeper_path(@beekeeper), method: :delete, data:{confirm: 'A You sure?'} %>
				|
				<%=link_to  'Back', :back, class: "btn btn-secondary"%></strong>
			</small>
		</section>   
</article>		
				 