config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html  
  
  resources :products
  
  resources :films
  
  resources :galleries
  
  resources :beekeepers
  
  resources :specifications
  
  resources :articles do
     resources :comments
  end
  
  root to: "welcome#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
   
   has_many :comments, dependent: :destroy 
   
   validates :author, presence: true, length: {minimum: 3}
   validates :text, presence: true, length: {minimum: 3}   
  
end

app/models/beekeeper.rb
class Beekeeper < ApplicationRecord
   mount_uploader :image, ImageUploader    	
   mount_uploader :image1, ImageUploader	
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/film.rb
class Film < ApplicationRecord
    
	mount_uploader :video, VideoUploader
	
	validates :title, presence: true,
                     length: {minimum: 3}
	
	
    			 
				 
end

app/models/gallery.rb
class Gallery < ApplicationRecord
   mount_uploader :image, ImageUploader
   
   validates :title, presence: true, length: {minimum: 3}
   validates :image, presence: true
   
end

app/models/product.rb
class Product < ApplicationRecord
    validates :title, presence: true,
                     length: {minimum: 3}
	validates :text, presence: true,
                     length: {minimum: 3}
    
	mount_uploader :image, ImageUploader
    	
	mount_uploader :image1, ImageUploader				 
end

app/models/specification.rb
class Specification < ApplicationRecord
   mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
	before_action :authenticate_user!, except: [:index, :show]
   
   def index
     @articles = Article.all
   end
   
   def show
      @article = Article.find(params[:id])   
   end
   
   def new
     @article = Article.new
   end
   
   def create
     @article = Article.new(article_params)
		
		if (@article.save)
		    @article.update(email: current_user.email)
			redirect_to @article
        else
            render 'new'
        end	   
   end
   
   def edit
      @article = Article.find(params[:id])
   end 
   
   def update     
	 @article = Article.find(params[:id])
	 
	 if @article.update(article_params)
	    redirect_to @article
	 else
        render 'edit'
     end  
   end
   
    def destroy
	    @article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path	 
	 end
   
    private
	 
	 def article_params
	     params.require(:article).permit(:text, :email, :author)
	 
	 end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   
    before_action :authenticate_user!, except: [:index,:show]
	
   def create
     @article = Article.find(params[:article_id])
	 @comment = @article.comments.create(comment_params)
	 @comment.update(email: current_user.email)
	 redirect_to article_path(@article)
   end
   
   def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
   
   private
   
   def comment_params
    
	params.require(:comment).permit(:commenter, :body)
     
   end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
     def index
	   @films = Film.all
	 end
	 
	 def show
	   @film = Film.find(params[:id])
	 end
	 
	 def new
	   @film = Film.new
	 end
	 
	 def edit
	   @film = Film.find(params[:id])
	 end
	 
	  def update
	   @film = Film.find(params[:id])
	   
	   if @film.update(film_params) 
	      redirect_to @film
		else
           render 'edit'   
	   end
	 end
	 
	 
	 def create
	    @film = Film.new(film_params)
		
		if (@film.save)
   		  redirect_to @film
        else
            render 'new'
        end			
	 end
   
   def destroy
     @film = Film.find(params[:id])
	 @film.destroy
	 redirect_to films_path
   end
   
	
    private	
	
	 def film_params
	    params.require(:film).permit(:title,:text,:video)
	 end
end

app/controllers/specifications_controller.rb
class SpecificationsController < ApplicationController
   
   def index 
      @specifications = Specification.all
   end
   
   def show
     @specification = Specification.find(params[:id])
   end
   
   def new            
     @specification = Specification.new
   end
   
   def create
   
     @specification = Specification.new(specification_params)
		
		if (@specification.save)
		    redirect_to @specification
        else
            render 'new'
        end	   
   end
   
   def edit
      @specification = Specification.find(params[:id])
   end
   
   def update 
     @specification = Specification.find(params[:id])
	 
	 if  @specification.update(specification_params)
	     redirect_to @specification	 
	 else
	     render 'edit'
	 end
   
   end
   
   def destroy
      @specification = Specification.find(params[:id])
	  
	  @specification.destroy
	  redirect_to @specifications_path

   end
   
   private
   
   def specification_params
     params.require(:specification).permit(:title,:text,:image)
      
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/beekeepers_helper.rb
module BeekeepersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/specifications_helper.rb
module SpecificationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/specifications/_form.html.erb
<%= form_for @specification, html: {multipart: true} do |f| %>

    <% if @specification.errors.any? %>
		<div class = "alert alert-danger">
		  <h2>
			<%=t('common.errors')%>
		  </h2>
		  <ul>
			<% @specification.errors.full_messages.each do |msg| %>
			  <li><%= msg %></li>
			<% end %>
		  </ul>
		</div>
    <% end %>	

	<div class="form-group">
	   <strong><%= f.label :'title:' %></strong><br>
	   <%= f.text_field :title, class:"form-control"%>	   
	</div>	
			
	<div class="form-group">
	   <strong><%= f.label :'image:' %></strong><br>
	   <%=f.file_field :image %>
	 </div>
	
	<div class="form-group">
	   <strong><%= f.label :'text:' %></strong><br>
	   <%=f.text_area  :text, class:"form-control", cols: 75, rows: 5 %>
	</div>
	
	<div class="form-group">
	  <%=f.submit :'save', class:"btn btn-primary"%>
	  <%=link_to  'back', :back, class: "btn btn-secondary"%>	  
	</div>
	
<% end %>

app/views/specifications/edit.html.erb
<h5>Editing specification</h5>

<%= render 'form' %>

app/views/specifications/index.html.erb
<%@val = 'Specifications'%>

 <% @specifications.each do |specification| %>
  <article class="post"> 
   	<section class="post-head">	
             <br>
			 
			 <% if  user_signed_in? %>
                <% if  current_user.admin? %>
                   <h4><%= link_to specification.title, specification_path(specification) %></h4>
				<% else %>
                   	<h4><%= specification.title %></h4>			
                <% end %>
					
			  <% else %>
				     <h4><%= specification.title %></h4>
			 <% end %>		 
		
	</section>
	
	
		 
		<div class="container">  
		  
		   <%=image_tag specification.image.url(:large), class:"img-show" if specification.image?%><br>
		   
		  
		</end>
        
            <%= specification.text %>         			
    
   </article><br> 	
  <%end%>


<% if  user_signed_in? %>
 <% if  current_user.admin? %>
   <div class="actions">  
	<%=link_to 'Add specification', new_specification_path, class:"btn btn-primary"%>
	</div>
 <%end%>
<%end%>	
 

app/views/specifications/new.html.erb
<h5>New specification</h5>
<%= render 'form' %>

app/views/specifications/show.html.erb
<%@val = 'Specification'%>

  <article class="post">
  
		 <section class="post-head "> 
			<h4><%= @specification.title %></h4>
		 </section>	
				 
			 
		<section class="container">	       
			   
			   <%=image_tag @specification.image.url(:large), class:"img-show" if @specification.image?%>
		</section>	  
		 
         <%= @specification.text %>			
    
		 
		 
  

		<section class="post-head ">				
			<small>
				<%=link_to 'Edit', edit_specification_path(@specification)%>
				|
				<%=link_to 'Delete', specification_path(@specification), method: :delete, data:{confirm: 'A You sure?'} %>
				|
				<%=link_to  'Back', :back, class: "btn btn-secondary"%></strong>
			</small>
		</section>   
</article>		
				 